# Generated by Django 6.0.1 on 2026-01-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('mens', 'mens'), ('womens', 'womens'), ('kids', 'kids')], default='mens', max_length=200)),
                ('size', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=200)),
            ],
        ),
    ]
